# Project information
site_name: Jared Peeler
site_url: https://deceasedvector.github.io/portfolio

# Repository
repo_url: https://github.com/deceasedvector/portfolio
repo_name: deceasedvector/portfolio

# Copyright
copyright: Copyright &copy; 2024 Jared Peeler

# Configuration
theme:
  name: material
  custom_dir: overrides/
  font:
    text: Roboto
  features:
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - search.highlight
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.share
  palette:
      primary: custom
      accent: custom
  logo: assets\images\logo-01.svg
  favicon: assets\images\logo-01.svg

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: deceasedvector
      repo: portfolio
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Additional configuration
extra:
#  version:
#    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deceasedvector
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaredpeeler
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:

  - index.md
  - Writing Samples:
    - conceptual-overview.md
    - sop.md
    - how-to.md
    - feature-article.md
    - user-guide-hardware.md
    - video.md